# Generated by Django 5.2.8 on 2025-11-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='secondary_images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
