# Generated by Django 5.2.8 on 2025-12-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_pod_id_alter_orderitem_price_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='product',
            name='pod_id',
            field=models.CharField(blank=True, help_text='The Printify Blueprint/Product ID (Required for Shipping)', max_length=100, null=True),
        ),
    ]
