# Generated by Django 5.2.8 on 2025-12-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_videoad_alter_orderitem_price_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoad',
            name='placement',
            field=models.CharField(choices=[('LIST', 'Product List Page (Catalog)'), ('DETAIL', 'Product Detail Page'), ('CART', 'Shopping Cart Page'), ('CHECKOUT', 'Checkout Page')], default='LIST', help_text='Select which page this ad should appear on.', max_length=20),
        ),
    ]
