# Generated by Django 6.0.1 on 2026-03-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_videoad_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='products/main/'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='products/variants/'),
        ),
    ]
