# Generated by Django 5.2.8 on 2026-05-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_image_file_productvariant_variant_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoad',
            name='placement',
            field=models.CharField(choices=[('HOME', 'Home Page (Landing)'), ('LIST', 'Product List Page (Catalog)'), ('DETAIL', 'Product Detail Page'), ('CART', 'Shopping Cart Page'), ('CHECKOUT', 'Checkout Page')], default='LIST', help_text='Select which page this ad should appear on.', max_length=20),
        ),
    ]
