# Generated by Django 5.2.8 on 2026-05-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_country_order_phone_order_shipping_cost_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='order',
            name='pod_order_id',
            field=models.CharField(blank=True, help_text='Order ID returned by Printify API', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pod_id',
            field=models.CharField(blank=True, help_text='The Printify Published Product ID (Required for Shipping)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='pod_id',
            field=models.CharField(help_text='The unique 10-digit Printify Variant ID.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='videoad',
            name='link_url',
            field=models.URLField(blank=True, help_text='Where should this ad link to?', null=True),
        ),
    ]
