# Generated by Django 6.0.1 on 2026-05-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_productvariant_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.CharField(blank=True, help_text='Shipping carrier name e.g. USPS, DHL', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Tracking number from carrier', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_url',
            field=models.URLField(blank=True, help_text='Tracking URL from Printful', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pod_order_id',
            field=models.CharField(blank=True, help_text='Order ID returned by Printful API', max_length=100, null=True),
        ),
    ]
