# Generated by Django 5.2.8 on 2026-05-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_carrier_order_tracking_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('product_type', models.CharField(choices=[('tshirt', 'T-Shirt'), ('hoodie', 'Hoodie')], max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('color_preference', models.CharField(blank=True, help_text='Preferred base colour e.g. Black, White, Navy', max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('custom_text', models.CharField(blank=True, help_text='Name, slogan, or text to print', max_length=300)),
                ('placement', models.CharField(blank=True, help_text='Where should the design go? e.g. Front centre, Back, Left chest', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Any additional instructions or references')),
                ('image_1', models.ImageField(blank=True, help_text='Primary design image (PNG/SVG preferred, min 300 DPI)', null=True, upload_to='custom_orders/')),
                ('image_2', models.ImageField(blank=True, help_text='Secondary / alternate image (optional)', null=True, upload_to='custom_orders/')),
                ('image_3', models.ImageField(blank=True, help_text='Additional reference image (optional)', null=True, upload_to='custom_orders/')),
                ('status', models.CharField(choices=[('NEW', 'New Request'), ('REVIEWING', 'Under Review'), ('QUOTED', 'Quote Sent'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected')], default='NEW', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (not shown to customer)')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom Order Request',
                'verbose_name_plural': 'Custom Order Requests',
                'ordering': ('-created',),
            },
        ),
    ]
