# Generated by Django 5.2.8 on 2026-05-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_passwordresetotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='customorderrequest',
            name='deadline',
            field=models.DateField(blank=True, help_text="Customer's requested deadline (if any)", null=True),
        ),
        migrations.AddField(
            model_name='customorderrequest',
            name='font_style',
            field=models.CharField(blank=True, help_text='Requested font style e.g. Bold Block, Script', max_length=100),
        ),
        migrations.AddField(
            model_name='customorderrequest',
            name='image_1_placement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customorderrequest',
            name='image_2_placement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customorderrequest',
            name='image_3_placement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customorderrequest',
            name='instagram',
            field=models.CharField(blank=True, help_text='Customer Instagram handle (optional)', max_length=100),
        ),
        migrations.AddField(
            model_name='customorderrequest',
            name='referral',
            field=models.CharField(blank=True, help_text='How the customer heard about HOXOBIL', max_length=100),
        ),
        migrations.AddField(
            model_name='customorderrequest',
            name='technique',
            field=models.CharField(blank=True, help_text='Print technique: dtg, screen, embroidery, vinyl', max_length=50),
        ),
        migrations.AddField(
            model_name='customorderrequest',
            name='text_color',
            field=models.CharField(blank=True, help_text='Requested text colour e.g. White, Gold', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='customorderrequest',
            name='product_type',
            field=models.CharField(choices=[('tshirt', 'T-Shirt (Classic)'), ('oversized-tee', 'Oversized Tee'), ('polo', 'Polo Shirt'), ('hoodie', 'Hoodie'), ('crewneck', 'Crewneck Sweatshirt'), ('longsleeve', 'Long Sleeve Shirt'), ('joggers', 'Jogger Pants'), ('shorts', 'Shorts'), ('zip-hoodie', 'Zip-Up Hoodie'), ('varsity', 'Varsity Jacket'), ('track-jacket', 'Track Jacket'), ('cap', 'Cap / Dad Hat'), ('beanie', 'Beanie'), ('tote', 'Tote Bag')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='pod_id',
            field=models.CharField(blank=True, help_text='The Printful Published Product ID (Required for Shipping)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='pod_id',
            field=models.CharField(help_text='The unique Printful Variant ID.', max_length=100, unique=True),
        ),
    ]
