# Generated by Django 5.2.8 on 2026-05-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_supportchat_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='print_areas',
            field=models.JSONField(blank=True, default=list, help_text='Allowed catalog print coordinates and placement metrics synced directly from Printful backend API mappings.'),
        ),
    ]
