# Generated by Django 6.0.1 on 2026-05-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_product_print_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image_field',
            field=models.ImageField(blank=True, null=True, upload_to='chat_uploads/%Y/%m/%d/'),
        ),
    ]
