# Generated by Django 6.0.6 on 2026-06-21 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_chatmessage_image_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_file', models.ImageField(upload_to='design_submissions/originals/')),
                ('admin_proof', models.ImageField(blank=True, null=True, upload_to='design_submissions/proofs/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROOF_SENT', 'Proof Sent'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PRODUCTION', 'Production')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customorderrequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='passwordresetotp',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={},
        ),
        migrations.AlterModelOptions(
            name='supportchat',
            options={},
        ),
        migrations.AlterModelOptions(
            name='videoad',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='shop_order_created_3ffca3_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_slug_76971b_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_availab_47d513_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_created_661b12_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='shop_produc_pod_id_93c595_idx',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='customorderrequest',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='customorderrequest',
            name='color_preference',
        ),
        migrations.RemoveField(
            model_name='customorderrequest',
            name='custom_text',
        ),
        migrations.RemoveField(
            model_name='customorderrequest',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='customorderrequest',
            name='font_style',
        ),
        migrations.RemoveField(
            model_name='customorderrequest',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='customorderrequest',
            name='image_1_placement',
        ),
        migrations.RemoveField(
            model_name='customorderrequest',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='customorderrequest',
            name='image_2_placement',
        ),
        migrations.RemoveField(
            model_name='customorderrequest',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='customorderrequest',
            name='image_3_placement',
        ),
        migrations.RemoveField(
            model_name='customorderrequest',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='customorderrequest',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='customorderrequest',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customorderrequest',
            name='placement',
        ),
        migrations.RemoveField(
            model_name='customorderrequest',
            name='referral',
        ),
        migrations.RemoveField(
            model_name='customorderrequest',
            name='technique',
        ),
        migrations.RemoveField(
            model_name='customorderrequest',
            name='text_color',
        ),
        migrations.RemoveField(
            model_name='customorderrequest',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='videoad',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='videoad',
            name='link_url',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='image_field',
            field=models.ImageField(blank=True, null=True, upload_to='chat_uploads/'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender_type',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], max_length=10),
        ),
        migrations.AlterField(
            model_name='customorderrequest',
            name='product_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customorderrequest',
            name='status',
            field=models.CharField(default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='carrier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pod_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pod_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pod_service',
            field=models.CharField(blank=True, choices=[('PFT', 'Printful'), ('PFY', 'Printify')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='print_areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='pod_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='videoad',
            name='placement',
            field=models.CharField(default='LIST', max_length=20),
        ),
        migrations.AlterField(
            model_name='videoad',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='videoad',
            name='video_file',
            field=models.FileField(upload_to='ads/videos/'),
        ),
        migrations.AddField(
            model_name='designsubmission',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_submissions', to='shop.supportchat'),
        ),
        migrations.AddField(
            model_name='designsubmission',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.order'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='secondary_images',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='variant_image_file',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='variant_images',
        ),
    ]
