# Generated by Django 6.0.6 on 2026-06-21 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_designsubmission_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designsubmission',
            old_name='user_file',
            new_name='design_file',
        ),
        migrations.RenameField(
            model_name='designsubmission',
            old_name='admin_proof',
            new_name='proof_image',
        ),
        migrations.RenameField(
            model_name='designsubmission',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='designsubmission',
            name='status',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.designsubmission'),
        ),
        migrations.AddField(
            model_name='designsubmission',
            name='admin_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='designsubmission',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designsubmission',
            name='design_file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designsubmission',
            name='garment',
            field=models.CharField(default='Default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designsubmission',
            name='placement_zone',
            field=models.CharField(default='Front', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designsubmission',
            name='product_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productvariant'),
        ),
        migrations.AddField(
            model_name='designsubmission',
            name='proof_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designsubmission',
            name='proof_status',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Pending Admin Review'), ('PROOF_SENT', 'Proof Sent to Customer'), ('APPROVED', 'Approved by Customer'), ('REJECTED', 'Rejected / Needs Changes'), ('IN_PRODUCTION', 'In Production')], default='PENDING_REVIEW', max_length=20),
        ),
    ]
