# Generated by Django 6.0.6 on 2026-06-23 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_rename_user_file_designsubmission_design_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDesignTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=150, null=True)),
                ('garment_item', models.CharField(help_text='e.g. Premium Polo Shirt, Streetwear Cap', max_length=100)),
                ('garment_color', models.CharField(blank=True, max_length=50, null=True)),
                ('garment_size', models.CharField(blank=True, max_length=20, null=True)),
                ('custom_text', models.TextField(help_text='The exact text the customer wants printed/embroidered.')),
                ('typography_style', models.CharField(blank=True, help_text='e.g. Minimalist, Streetwear Gothic', max_length=100, null=True)),
                ('placement', models.CharField(blank=True, help_text='e.g. Left Chest, Center Back', max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Design Team Review'), ('drafting', 'Mockup in Progress'), ('review', 'Sent to Customer for Approval'), ('approved', 'Approved & Ready for Production')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
