# Generated by Django 6.0.6 on 2026-06-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_customdesignticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdesignticket',
            name='design_team_mockup',
            field=models.ImageField(blank=True, help_text='Upload the finished PNG/JPG proof here to send it to the customer.', null=True, upload_to='design_mockups/'),
        ),
        migrations.AlterField(
            model_name='customdesignticket',
            name='status',
            field=models.CharField(choices=[('Pending Design Team Review', 'Pending Design Team Review'), ('Mockup in Progress', 'Mockup in Progress'), ('Sent to Customer for Approval', 'Sent to Customer for Approval'), ('Approved & Ready for Production', 'Approved & Ready for Production')], default='Pending Design Team Review', max_length=50),
        ),
    ]
