# Generated by Django 6.0.6 on 2026-06-26 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_customdesignticket_design_team_mockup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdesignticket',
            name='invoice_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total price for this custom order in NGN. Set this, then the invoice is sent automatically when the customer approves the mockup.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='customdesignticket',
            name='invoice_sent',
            field=models.BooleanField(default=False, help_text="True once the payment link has been dropped into the customer's chat."),
        ),
        migrations.AddField(
            model_name='customdesignticket',
            name='linked_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_ticket', to='shop.order'),
        ),
        migrations.AddField(
            model_name='customdesignticket',
            name='printful_product_id',
            field=models.CharField(blank=True, help_text="Paste the Printful Product ID here, then click 'Fetch Mockup from Printful'.", max_length=100, null=True),
        ),
    ]
