# Generated by Django 6.0.6 on 2026-06-27 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_botknowledge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unknownquestion',
            name='converted_to',
        ),
        migrations.RemoveField(
            model_name='unknownquestion',
            name='user',
        ),
        migrations.AddField(
            model_name='customdesignticket',
            name='invoice_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total price in NGN.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='customdesignticket',
            name='invoice_sent',
            field=models.BooleanField(default=False, help_text='True once payment link sent to customer.'),
        ),
        migrations.AddField(
            model_name='customdesignticket',
            name='linked_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_ticket', to='shop.order'),
        ),
        migrations.AddField(
            model_name='customdesignticket',
            name='printful_product_id',
            field=models.CharField(blank=True, help_text='Paste the Printful Product ID here.', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='BotKnowledge',
        ),
        migrations.DeleteModel(
            name='UnknownQuestion',
        ),
    ]
