# Generated by Django 6.0.6 on 2026-06-27 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_remove_unknownquestion_converted_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField(help_text="Comma-separated keywords that trigger this answer. e.g. 'delivery time, how long, when will i get'")),
                ('answer', models.TextField(help_text='The exact response the bot will give when a customer asks this.')),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bot Knowledge',
                'verbose_name_plural': 'Bot Knowledge Base',
                'ordering': ['-times_used'],
            },
        ),
        migrations.CreateModel(
            name='UnknownQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('session_step', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('answered', 'Converted to Answer'), ('ignored', 'Ignored')], default='pending', max_length=10)),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
                ('converted_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_questions', to='shop.botknowledge')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unknown Question',
                'verbose_name_plural': 'Unknown Questions (Train the Bot)',
                'ordering': ['-asked_at'],
            },
        ),
    ]
