# Generated by Django 6.0.6 on 2026-07-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_botknowledge_unknownquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pod_service',
            field=models.CharField(blank=True, choices=[('PFT', 'Printful'), ('PFY', 'Printify'), ('APQ', 'Apliiq')], max_length=20),
        ),
    ]
