# Generated by Django 6.0.6 on 2026-07-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_alter_product_pod_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='color_hex',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
