# Generated by Django 6.0.6 on 2026-07-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_productvariant_color_hex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='color_hex',
        ),
        migrations.AlterField(
            model_name='product',
            name='pod_service',
            field=models.CharField(blank=True, choices=[('PFT', 'Printful'), ('PFY', 'Printify')], max_length=20),
        ),
    ]
