# Generated by Django 6.0.6 on 2026-07-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='abandonment_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='Set once a cart-abandonment reminder has been sent for this order, to avoid emailing twice.', null=True),
        ),
    ]
