# Generated by Django 6.0.6 on 2026-07-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_order_abandonment_email_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_customizable',
            field=models.BooleanField(default=False, help_text="Auto-set during sync when the Printful title is prefixed with 'c#'. Marks this as a blank garment customers can request custom designs on, instead of a finished admin-designed listing."),
        ),
    ]
