# Generated by Django 6.0.6 on 2026-07-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='settlement_release_at',
            field=models.DateTimeField(blank=True, help_text="Set when payment is confirmed. The order is held at status 'PENDING_SETTLEMENT' and is not sent to Printful until this time passes — see the release_settled_orders management command.", null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('PENDING_SETTLEMENT', 'Paid — Awaiting Settlement'), ('POD_SENT', 'Sent to POD'), ('FULFILLED', 'Fulfilled by POD'), ('SHIPPED', 'Shipped'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
