# Generated by Django 6.0.6 on 2026-09-09 17:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_order_flutterwave_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizableBlankProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Customizable Blank Garment',
                'verbose_name_plural': 'Customizable Blank Garments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='RegularProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Customized Product',
                'verbose_name_plural': 'Customized Products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.product',),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created'], name='shop_order_user_id_cebc86_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'paid', 'settlement_release_at'], name='shop_order_status_0850e9_idx'),
        ),
    ]
