# Generated by Django 6.0.6 on 2026-09-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_customizableblankproduct_regularproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('PENDING_SETTLEMENT', 'Paid — Awaiting Settlement'), ('SUBMITTING', 'Submitting to Production'), ('POD_SENT', 'Sent to POD'), ('FULFILLED', 'Fulfilled by POD'), ('SHIPPED', 'Shipped'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
