# Generated by Django 6.0.6 on 2026-09-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='twilio_message_sid',
            field=models.CharField(blank=True, max_length=34, null=True, unique=True),
        ),
    ]
