# Generated by Django 6.0.6 on 2026-09-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_chatmessage_twilio_message_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='botknowledge',
            name='category',
            field=models.CharField(default='general', max_length=80),
        ),
        migrations.AddField(
            model_name='botknowledge',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supportchat',
            name='human_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='image_field',
            field=models.FileField(blank=True, null=True, upload_to='chat_uploads/'),
        ),
    ]
